# Training configuration for image segmentation

# Project settings
project: "cslics_detection"
name: "cslics_combined_20250930"
model_path: "yolov8n.pt"
yaml_path: "Data/cslics/2023_2024_combined_dataset/cslics_2023_2024_subsurface_M12.yaml"

# Training parameters
classes: [0]  # Coral: Alive and Dead
pretrained: true
epochs: 1000
batch_size: 0.65
workers: 4
save_period: 10
patience: 25
mask_overlap: false
device: 0 # device = [0, 1, 2, 3]

# Augmentation parameters
image_size: 640
scale: 0.2
flipud: 0.5
fliplr: 0.5